package com.example.crud.entity;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name="crud")
public class MyEntity {
    @Id
    @Column(name = "id",length = 100)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Autogenerated Id")
    private int id;
    @Column(name = "name",length = 100)
    @ApiModelProperty(value = "User Name")
    @NotNull(message = "Name not null")
    private String name;
    @Column(name = "ph",length = 100)
    @ApiModelProperty(value = "Phone Number")
    @NotNull
    @Size(min = 10, message = "Enter your phone number must be 10 char")
    @Pattern(regexp = "^([1-9]\\d*|0)$")
    private String phoneNumber;
}
